import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type PO = { entityId: string; supplierName: string | null; orderedQuantity: number | null; confirmedQuantity: number | null; receivedQuantity: number; eta: string | null; status: string };
type Exception = { id: string; entityId: string; type: string; priority: number; details: Record<string, string | number>; eventIds: string[] };
type Event = { id: string; eventType: string; occurredAt: string; sourceRecordId: string; payload: Record<string, unknown> };
type Run = { id: string; cacheKey: string; status: string; fallbackTier?: string; usage?: { inputTokens?: number; outputTokens?: number; totalTokens?: number }; request: { analysisType: string }; createdAt: string };
type Source = { id: string; sourceType: string; importedAt: string };
const json = <T,>(url: string) => fetch(url).then((response) => response.json() as Promise<T>);

function App() {
  const [pos, setPos] = useState<PO[]>([]); const [exceptions, setExceptions] = useState<Exception[]>([]); const [selected, setSelected] = useState<string | null>(null); const [timeline, setTimeline] = useState<Event[]>([]); const [tab, setTab] = useState<"attention" | "import" | "runs">("attention");
  const load = () => Promise.all([json<PO[]>("/api/purchase-orders"), json<Exception[]>("/api/exceptions")]).then(([orders, attention]) => { setPos(orders); setExceptions(attention); });
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (selected) void json<Event[]>(`/api/purchase-orders/${selected}/timeline`).then(setTimeline); }, [selected]);
  const current = pos.find((po) => po.entityId === selected);
  return <main>
    <header><div><span className="eyebrow">PROCUREBRAIN / OPERATIONS</span><h1>Purchase order memory</h1><p className="muted">A compact view of what changed, what is late, and what needs a human next.</p></div><button onClick={() => void load()}>Refresh</button></header>
    <nav><button className={tab === "attention" ? "active" : ""} onClick={() => setTab("attention")}>Needs attention <b>{exceptions.length}</b></button><button className={tab === "import" ? "active" : ""} onClick={() => setTab("import")}>Import & review</button><button className={tab === "runs" ? "active" : ""} onClick={() => setTab("runs")}>Analysis history</button></nav>
    {tab === "import" ? <Import onDone={() => { void load(); }} /> : tab === "runs" ? <History /> : <section className="layout"><aside><h2>Needs attention</h2>{exceptions.map((item) => <button className="exception" key={item.id} onClick={() => setSelected(item.entityId)}><span className="severity">P{item.priority}</span><span><strong>{item.type.replaceAll("_", " ")}</strong><small>{item.entityId} · {Object.values(item.details).join(" / ")}</small></span></button>)}</aside><section><h2>Purchase orders</h2><div className="cards">{pos.map((po) => <button className={`po ${selected === po.entityId ? "selected" : ""}`} key={po.entityId} onClick={() => setSelected(po.entityId)}><span className="po-id">{po.entityId}</span><strong>{po.supplierName ?? "Unknown supplier"}</strong><span>{po.receivedQuantity} / {po.confirmedQuantity ?? po.orderedQuantity ?? "—"} received</span><span className="status">{po.status} {po.eta ? `· ETA ${po.eta}` : ""}</span></button>)}</div>{current && <Detail po={current} timeline={timeline} />}</section></section>}
  </main>;
}

function Detail({ po, timeline }: { po: PO; timeline: Event[] }) { return <article className="detail"><div className="detail-head"><div><span className="eyebrow">PURCHASE ORDER DETAIL</span><h2>{po.entityId} · {po.supplierName}</h2></div><span className="pill">{po.status}</span></div><div className="facts"><div><small>Ordered</small><strong>{po.orderedQuantity ?? "—"}</strong></div><div><small>Confirmed</small><strong>{po.confirmedQuantity ?? "—"}</strong></div><div><small>Received</small><strong>{po.receivedQuantity}</strong></div><div><small>ETA</small><strong>{po.eta ?? "—"}</strong></div></div><h3>Timeline & evidence</h3><ol className="timeline">{timeline.map((event) => <li key={event.id}><time>{new Date(event.occurredAt).toLocaleDateString()}</time><div><strong>{event.eventType.replaceAll("_", " ")}</strong><small>source: <a href={`/api/sources/${encodeURIComponent(event.sourceRecordId)}`} target="_blank" rel="noreferrer">{event.sourceRecordId}</a> · evidence: {event.id}</small></div></li>)}</ol></article>; }

function Import({ onDone }: { onDone: () => void }) {
  const [csv, setCsv] = useState("po,event_type,occurred_at,quantity\nPO-1001,RECEIPT,2025-02-01T00:00:00Z,2"); const [kind, setKind] = useState("supplier-updates"); const [message, setMessage] = useState(""); const [analysis, setAnalysis] = useState(""); const [supplierText, setSupplierText] = useState(""); const [document, setDocument] = useState<File | null>(null);
  const submit = async () => { const response = await fetch(`/api/imports/${kind}`, { method: "POST", headers: { "content-type": "text/csv" }, body: csv }); const result = await response.json() as { inserted?: number; rejected?: unknown[]; unresolved?: unknown[]; error?: unknown }; setMessage(response.ok ? `Imported ${result.inserted ?? 0} event(s); ${result.rejected?.length ?? 0} rejected, ${result.unresolved?.length ?? 0} unresolved.` : String(result.error ?? "Import failed")); if (response.ok) onDone(); };
  const analyzeCsv = async () => { const response = await fetch("/api/analysis/csv", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ csv }) }); const result = await response.json(); setAnalysis(JSON.stringify(result, null, 2)); };
  const analyzeText = async () => { const response = await fetch("/api/analysis/supplier-text", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text: supplierText }) }); setAnalysis(JSON.stringify(await response.json(), null, 2)); };
  const analyzeDocument = async () => { if (!document) return; const response = await fetch("/api/analysis/document", { method: "POST", headers: { "content-type": document.type, "idempotency-key": `document-${document.name}-${document.size}` }, body: document }); setAnalysis(JSON.stringify(await response.json(), null, 2)); };
  return <div className="workspace"><section className="import"><h2>Import operational CSV</h2><p className="muted">CSV normalization is deterministic and uses no model tokens. Original evidence remains attached to canonical events.</p><label>Record type<select value={kind} onChange={(event) => setKind(event.target.value)}><option value="purchase-orders">Purchase orders</option><option value="supplier-updates">Supplier updates</option><option value="receipts">Receipts</option><option value="followups">Follow-ups</option></select></label><textarea aria-label="CSV content" value={csv} onChange={(event) => setCsv(event.target.value)} /><div className="actions"><button onClick={() => void submit()}>Normalize & import</button><button className="secondary" onClick={() => void analyzeCsv()}>Preview analysis</button></div>{message && <p role="status">{message}</p>}</section><section className="import review"><h2>Supplier text / document review</h2><p className="muted">Images and PDFs are processed with local PaddleOCR first. Extracted text goes to the configured model; image vision is used only if image OCR fails. PDF failures stay reviewable. AI output is a proposal; review it before recording an operational event.</p><label>Supplier message<textarea aria-label="Supplier message" value={supplierText} onChange={(event) => setSupplierText(event.target.value)} placeholder="Paste a supplier update…" /></label><button onClick={() => void analyzeText()} disabled={!supplierText.trim()}>Analyze supplier text</button><label className="file-label">Supplier image or PDF<input type="file" accept="image/png,image/jpeg,image/webp,application/pdf,.pdf" onChange={(event) => setDocument(event.target.files?.[0] ?? null)} /></label>{document && <p className="muted">Selected: {document.name} · {(document.size / 1024).toFixed(0)} KB</p>}<button onClick={() => void analyzeDocument()} disabled={!document}>OCR & analyze document</button>{analysis && <pre className="result" aria-live="polite">{analysis}</pre>}</section><Sources /></div>;
}

function Sources() { const [sources, setSources] = useState<Source[]>([]); const [source, setSource] = useState<unknown>(null); useEffect(() => { void json<Source[]>("/api/sources").then(setSources); }, []); return <section className="import sources"><h2>Imported source evidence</h2>{sources.length ? sources.map((item) => <button className="source-row" key={item.id} onClick={() => void json(`/api/sources/${encodeURIComponent(item.id)}`).then(setSource)}><strong>{item.sourceType}</strong><span>{item.id}</span><small>{new Date(item.importedAt).toLocaleString()}</small></button>) : <p className="muted">No imported sources yet.</p>}{Boolean(source) && <pre className="result">{JSON.stringify(source, null, 2)}</pre>}</section>; }

function History() { const [runs, setRuns] = useState<Run[]>([]); const [selected, setSelected] = useState<Run | null>(null); const refresh = () => void json<Run[]>("/api/analysis/runs").then(setRuns); useEffect(refresh, []); return <section className="history"><div className="detail-head"><div><h2>Analysis runs</h2><p className="muted">Cache replay, review outcomes, fallback tier, and recorded model usage.</p></div><button className="secondary" onClick={refresh}>Refresh history</button></div>{runs.length ? runs.map((run) => <button className="run-row" key={run.cacheKey} onClick={() => { setSelected(run); void json<Run>(`/api/analysis/runs/${encodeURIComponent(run.cacheKey)}`).then(setSelected); }}><strong>{run.request.analysisType}</strong><span className={`run-status ${run.status}`}>{run.status}</span><small>{run.fallbackTier ?? "primary"} · {run.usage?.totalTokens ?? 0} tokens · {new Date(run.createdAt).toLocaleString()}</small></button>) : <p className="muted">No analysis runs yet.</p>}{selected && <pre className="result">{JSON.stringify(selected, null, 2)}</pre>}</section>; }

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
