import { useState } from "react";
import { channelLabel, dateLabel, daysBetween, orderName, readable, today, useResource } from "../api";
import { Badge, Empty, Icon, Modal, Notice, PanelHeading, RawDetails } from "../components/ui";
import type { Attention, DashboardData, OrderEvent, Page, PO, Source } from "../types";

const attentionTitles: Record<string, string> = { ETA_CHANGED: "Delivery date changed", LATE_PO: "Past delivery date", QUANTITY_SHORT: "Supplier cannot provide the full quantity", RECEIPT_SHORT: "Fewer goods received than expected", FOLLOWUP_OVERDUE: "Supplier reply overdue" };
export function AttentionList({ items, orders, onSelect }: { items: Attention[]; orders: PO[]; onSelect: (id: string) => void }) {
  return items.length ? <div className="attention-list">{items.slice(0, 6).map(item => {
    const order = orders.find(po => po.entityId === item.entityId);
    const info = item.type === "ETA_CHANGED" ? `${dateLabel(String(item.details.previousEta))} → ${dateLabel(String(item.details.newEta))}` : item.type === "LATE_PO" ? `Expected ${dateLabel(String(item.details.eta), true)}` : item.type === "QUANTITY_SHORT" ? `${item.details.confirmedQuantity} of ${item.details.orderedQuantity} units confirmed` : item.type === "RECEIPT_SHORT" ? `${item.details.receivedQuantity} of ${item.details.expectedQuantity} units received` : "Check the latest supplier response";
    return <button className="attention-item" key={item.id} onClick={() => onSelect(item.entityId)}><span className={`attention-symbol ${item.type === "LATE_PO" ? "red" : "amber"}`}><Icon name={item.type === "ETA_CHANGED" ? "calendar" : "warning"} size={17}/></span><span className="attention-copy"><strong>{attentionTitles[item.type] ?? readable(item.type)}</strong><span>{order ? orderName(order) : item.entityId} <span className="separator">·</span> {info}</span></span><Icon name="chevron" size={16}/></button>;
  })}</div> : <Empty title="Nothing needs attention" icon="check">Order issues will appear here as activity is recorded.</Empty>;
}

export function OrderTable({ orders, attention, search, compact = false, onSelect, onImport }: { orders: PO[]; attention: Attention[]; search: string; compact?: boolean; onSelect: (id: string) => void; onImport: () => void }) {
  const [filter, setFilter] = useState("all");
  const needingAttention = new Set(attention.map(item => item.entityId));
  const filtered = orders.filter(po => `${orderName(po)} ${po.supplierName ?? ""} ${po.status}`.toLowerCase().includes(search.toLowerCase()) && (filter === "all" || (filter === "attention" ? needingAttention.has(po.entityId) : po.status === "RECEIVED")));
  const shown = compact ? filtered.slice(0, 5) : filtered;
  return <section className="panel orders-panel"><PanelHeading title={compact ? "Orders" : "Your orders"} subtitle={`${orders.length} recorded ${orders.length === 1 ? "order" : "orders"}`} action={<div className="segmented" aria-label="Filter orders">{[["all", "All orders"], ["attention", "Needs attention"], ["received", "Received"]].map(([key, label]) => <button key={key} aria-pressed={filter === key} className={filter === key ? "selected" : ""} onClick={() => setFilter(key)}>{label}</button>)}</div>}/>
    {shown.length ? <><div className="table-scroll"><table className="data-table"><thead><tr><th>Order number</th><th>Supplier</th><th>Received</th><th>Delivery date</th><th>Status</th><th><span className="sr-only">Open order</span></th></tr></thead><tbody>{shown.map(po => {
      const expected = po.confirmedQuantity ?? po.orderedQuantity;
      const percent = expected && expected > 0 ? Math.min(100, po.receivedQuantity / expected * 100) : 0;
      const overdue = po.status !== "RECEIVED" && po.eta && po.eta < today();
      return <tr key={po.entityId}><td><button className="order-link" onClick={() => onSelect(po.entityId)}>{orderName(po)}</button><small className="cell-subtext">{po.orderedQuantity ?? "—"} units ordered</small></td><td><span className="supplier-cell"><span className="supplier-avatar">{(po.supplierName ?? "?").slice(0, 1)}</span><span>{po.supplierName ?? "Unknown supplier"}</span></span></td><td><span className="quantity-label">{po.receivedQuantity} <span>/ {expected ?? "—"}</span></span><span className="mini-progress"><span style={{ width: `${percent}%` }}/></span></td><td><span className={overdue ? "overdue" : ""}>{dateLabel(po.eta, true)}</span>{overdue && <small className="cell-subtext overdue">Past due</small>}</td><td><Badge value={po.status}>{compact && po.status === "PARTIALLY_RECEIVED" ? "Some received" : undefined}</Badge></td><td><button className="icon-button" aria-label={`Open ${orderName(po)}`} onClick={() => onSelect(po.entityId)}><Icon name="chevron" size={16}/></button></td></tr>;
    })}</tbody></table></div><div className="table-footer"><span>Showing {shown.length} of {filtered.length} {filter === "all" ? "orders" : "matching orders"}</span><span>Original messages and files are saved <Icon name="shield" size={14}/></span></div></> : <Empty icon="box" title={orders.length ? "No matching orders" : "Your first order starts here"}>{orders.length ? "Try another search or order filter." : "Import a CSV to start tracking delivery dates and supplier changes."}{!orders.length && <button className="button button-primary" onClick={onImport}><Icon name="upload" size={16}/> Import orders</button>}</Empty>}
  </section>;
}

export function Overview({ data, search, onSelect, navigate, onReview, onCapture }: { data: DashboardData; search: string; onSelect: (id: string) => void; navigate: (page: Page) => void; onReview: (id: string) => void; onCapture: () => void }) {
  const open = data.pos.filter(po => po.status !== "RECEIVED");
  const pending = data.proposals.filter(proposal => proposal.status === "PENDING");
  const late = data.attention.filter(item => item.type === "LATE_PO").length;
  const upcoming = open.filter(po => po.eta && po.eta >= today()).sort((a, b) => (a.eta ?? "").localeCompare(b.eta ?? "")).slice(0, 4);
  const stats = [
    { label: "Open orders", short: "Open orders", value: open.length, note: `${data.pos.filter(po => po.status === "RECEIVED").length} fully received`, icon: "box", page: "orders" as Page, tone: "sage" },
    { label: "Changes to check", short: "Check changes", value: pending.length, note: "Check before updating", icon: "review", page: "reviews" as Page, tone: "orange" },
    { label: "Needs attention", short: "Attention", value: data.attention.length, note: `${late} ${late === 1 ? "order" : "orders"} past delivery date`, icon: "warning", page: "orders" as Page, tone: "rose" },
    { label: "Supplier messages", short: "Messages", value: data.messages.length, note: `${data.messages.filter(message => message.processingStatus === "REVIEW_REQUIRED").length} need an order match`, icon: "inbox", page: "messages" as Page, tone: "blue" },
  ];
  return <><div className="metric-grid">{stats.map(stat => <button key={stat.label} className="metric" aria-label={`${stat.label}: ${stat.value}. ${stat.note}`} onClick={() => navigate(stat.page)}><span className="metric-top"><span className="metric-label-full">{stat.label}</span><span className="metric-label-short">{stat.short}</span><span className={`metric-icon ${stat.tone}`}><Icon name={stat.icon} size={19}/></span></span><strong>{stat.value.toLocaleString()}</strong><span className="metric-note">{stat.note}<Icon name="arrow" size={15}/></span></button>)}</div>
    <div className="overview-workspace">
      <div className="overview-main">
        {pending.length > 0 && <section className="panel"><PanelHeading title="Check these changes first" subtitle="The order stays the same until you approve a change" action={<button className="text-button" onClick={() => navigate("reviews")}>See all changes<Icon name="arrow" size={15}/></button>}/><div className="attention-list">{pending.slice(0, 3).map(change => { const order = data.pos.find(po => po.entityId === change.entityId); return <button className="attention-item" key={change.id} onClick={() => onReview(change.id)}><span className="attention-symbol amber"><Icon name="review" size={17}/></span><span className="attention-copy"><strong>{order ? orderName(order) : change.entityId} · {order?.supplierName ?? "Unknown supplier"}</strong><span>{change.proposalType === "ETA_CHANGE" ? `Suggested delivery date: ${dateLabel(change.payload.eta, true)}` : `Suggested quantity: ${change.payload.quantity ?? "—"} units`}</span></span><Icon name="chevron" size={16}/></button>; })}</div></section>}
        <section className="panel attention-panel"><PanelHeading title="Needs your attention" subtitle="Late deliveries and missing goods" action={<span className="count-pill">{data.attention.length} {data.attention.length === 1 ? "issue" : "issues"}</span>}/><AttentionList items={data.attention} orders={data.pos} onSelect={onSelect}/></section>
        <OrderTable orders={data.pos} attention={data.attention} search={search} compact onSelect={onSelect} onImport={() => navigate("imports")}/>
      </div>
      <aside className="overview-aside" aria-label="Supplier updates and deliveries">
        <section className="workflow-card"><h2>Let supplier updates come to you</h2><p>Connect Gmail to read supplier updates. Check the suggested change before updating the order.</p><div className="workflow-steps"><span><b>1</b> Connect a message channel</span><span><b>2</b> Check the change</span><span><b>3</b> Update the order</span></div><button className="button button-dark" onClick={() => navigate("connections")}><Icon name="mail" size={17}/>Connect Gmail</button><button className="text-button" onClick={onCapture}>Add a message yourself</button></section>
        <section className="panel"><PanelHeading title="Upcoming deliveries" subtitle="Orders due today or later"/>{upcoming.length ? <div className="delivery-list">{upcoming.map(po => <button key={po.entityId} onClick={() => onSelect(po.entityId)}><span className="date-tile"><small>{dateLabel(po.eta).split(" ")[0]}</small><strong>{new Date(`${po.eta}T00:00:00Z`).getUTCDate()}</strong></span><span><strong>{orderName(po)}</strong><small>{po.supplierName}</small></span><span className="delivery-days">{daysBetween(today(), po.eta) === 0 ? "Today" : `In ${daysBetween(today(), po.eta)} days`}</span><Icon name="chevron" size={16}/></button>)}</div> : <Empty icon="calendar" title="No upcoming deliveries">Add an order with a delivery date to see it here.</Empty>}</section>
        <section className="panel compact-guide"><PanelHeading title="Check the original message"/><div className="guide-row"><span><Icon name="shield" size={20}/></span><div><strong>Your changes are saved</strong><p>Read the supplier message before updating an order.</p></div></div><button className="text-button" onClick={() => navigate("practice")}>Try an example<Icon name="arrow" size={15}/></button></section>
      </aside>
    </div>
  </>;
}

export function OrderDetail({ po, attention, revision, onClose, onCapture }: { po: PO; attention: Attention[]; revision: number; onClose: () => void; onCapture: (id: string) => void }) {
  const { data: timeline, error, loading } = useResource<OrderEvent[]>(`/purchase-orders/${encodeURIComponent(po.entityId)}/timeline`, revision);
  const [sourceId, setSourceId] = useState<string | null>(null);
  const { data: source, error: sourceError, loading: sourceLoading } = useResource<Source>(sourceId ? `/sources/${encodeURIComponent(sourceId)}` : null);
  return <Modal title={orderName(po)} description={po.supplierName ?? "Supplier not recorded"} onClose={onClose} wide><div className="order-detail-summary"><Badge value={po.status}/><button className="button button-primary button-small" onClick={() => onCapture(po.entityId)}><Icon name="plus" size={16}/> Add message</button></div><div className="facts"><div><small>Ordered</small><strong>{po.orderedQuantity ?? "—"}<em> units</em></strong></div><div><small>Confirmed</small><strong>{po.confirmedQuantity ?? "—"}<em> units</em></strong></div><div><small>Received</small><strong>{po.receivedQuantity}<em> units</em></strong></div><div><small>Delivery date</small><strong>{dateLabel(po.eta, true)}</strong></div></div>{attention.some(item => item.entityId === po.entityId) && <div className="order-issues">{attention.filter(item => item.entityId === po.entityId).map(item => <span key={item.id}><Icon name="warning" size={14}/>{attentionTitles[item.type] ?? readable(item.type)}</span>)}</div>}<h3 className="section-label">Order history</h3>{error && <Notice tone="error">{error}</Notice>}{loading && !timeline && <p className="loading-label">Loading order history…</p>}<ol className="timeline">{timeline?.map(event => <li key={event.id}><span className="timeline-node"><Icon name={event.eventType === "PO_CREATED" ? "box" : event.eventType === "GOODS_RECEIVED" ? "check" : "calendar"} size={15}/></span><div><strong>{readable(event.eventType)}</strong><span>{typeof event.payload.eta === "string" ? `Delivery date: ${dateLabel(event.payload.eta, true)}` : typeof event.payload.quantity === "number" ? `${event.payload.quantity} units` : "Activity recorded"}</span><button className="text-button" onClick={() => setSourceId(event.sourceRecordId)}>View original message or file<Icon name="arrow" size={13}/></button></div><time>{dateLabel(event.occurredAt, true)}</time></li>)}</ol>{!loading && !error && !timeline?.length && <Empty title="No recorded activity"/>}{sourceError && <Notice tone="error">{sourceError}</Notice>}{sourceLoading && <p className="loading-label">Loading original record…</p>}{source && <section className="source-preview"><div className="detail-heading"><h3>{channelLabel(source.sourceType)} original record</h3><button className="icon-button" aria-label="Close original record" onClick={() => setSourceId(null)}><Icon name="close" size={16}/></button></div><pre className="original-text">{source.content ?? "Source content is unavailable."}</pre><RawDetails value={source}/></section>}</Modal>;
}
